{% set name = "napari-chatgpt" %}
{% set version = "2025.07.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari_chatgpt-{{ version }}.tar.gz
  # sha256 will need to be updated when publishing a new version

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling >=1.24
    - pip
  run:
    - python >=3.10
    - pip  # needed to install litemind from PyPI if not on conda-forge

    # Scientific computing
    - numpy >=1.26
    - scikit-image >=0.21
    - numba >=0.60
    - xarray >=2024.1.0,<2025  # Pin <2025: newer versions require Python 3.11+
    - matplotlib-base >=3.7

    # Web/API
    - fastapi >=0.109
    - uvicorn >=0.20
    - websockets >=11.0
    - httpx >=0.24

    # Qt/GUI
    - magicgui >=0.7
    - qtpy >=2.0
    - qtawesome >=1.0

    # Data/IO
    - imageio >=2.31
    - ome-zarr >=0.8
    - nbformat >=5.7
    - lxml >=4.9

    # Utilities
    - cryptography >=43.0
    - tabulate >=0.9
    - arbol
    - jedi >=0.18
    - black >=23.0

    # Note: litemind and ddgs must be installed via pip
    # as they are not available on conda-forge

test:
  imports:
    - napari_chatgpt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/royerlab/napari-chatgpt
  summary: A napari plugin providing Omega, an LLM-powered agent for image processing and analysis.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - royerloic
