"""Tool for querying the state of a napari viewer instance.

This module provides ``NapariViewerQueryTool``, an LLM-driven tool that
generates a ``query(viewer) -> str`` function to extract information from
the napari viewer, such as segment counts, layer metadata, or statistical
summaries.  The function runs on the Qt thread and its return value is
relayed back to the main agent.
"""

import traceback
from contextlib import redirect_stdout
from io import StringIO

from arbol import aprint, asection
from napari import Viewer

from napari_chatgpt.omega_agent.tools.base_napari_tool import BaseNapariTool
from napari_chatgpt.utils.python.dynamic_import import dynamic_import

_napari_viewer_query_prompt = """
**Context**
You write Python code to query a napari viewer instance for image processing and analysis tasks.

**Task:**
Implement a function `query(viewer) -> str` that queries the napari viewer and returns the answer as a string. Examples: count segments using `np.unique`, retrieve centroid coordinates, compute area/volume statistics, or return layer metadata.

**Instructions:**
{instructions}

{last_generated_code}

**Viewer Information:**
{viewer_information}

**System Information:**
{system_information}

**Request:**
{input}

**Answer in markdown:**
"""

_instructions = """
- Do **not** call the `query(viewer)` function yourself.
- Provide your answer **only** in Markdown format.
- Implement a function `query(viewer) -> str` that takes the viewer as a parameter and returns the answer as a string.
"""


class NapariViewerQueryTool(BaseNapariTool):
    """LLM-driven tool for querying the napari viewer state.

    Generates a ``query(viewer) -> str`` function that extracts information
    from the viewer (segment counts, layer metadata, statistics, etc.) and
    returns a short textual answer.  The function is dynamically imported and
    executed; its return value and any captured stdout are relayed back.

    Not suitable for returning large datasets (arrays, full coordinate lists).
    """

    def __init__(self, **kwargs):
        """Initialize the viewer query tool.

        Args:
            **kwargs: Forwarded to ``BaseNapariTool.__init__``.
        """
        super().__init__(**kwargs)

        self.name = "NapariViewerQueryTool"
        self.description = (
            "Use this tool when you need to a short answer to a question about the napari viewer, "
            "its state, or its layers (images, labels, points, tracks, shapes, and meshes). "
            "The input must be a plain text description of what you want to do, it should not contain code, it must not assume knowledge of our conversation, and it must be explicit about what is asked."
            "For instance, you can request to 'return the number of segments in the selected labels layer', 'return the total number of pixels/voxels in all image layers', or 'the number of unique colors' (selected layer is assumed by default). "
            "Important: this tool should not be used for requests that are expected to return large amounts of data, entire files, large tables or arrays (>60 entries)."
            "For instance, do not use this tool to list pixels of an image, to return the coordinates of all points in a points layer, or to list segments in a labels layer. "
            "This tool returns a short answer to the request. "
        )
        self.prompt = _napari_viewer_query_prompt
        self.instructions = _instructions
        self.save_last_generated_code = False

    def _run_code(self, query: str, code: str, viewer: Viewer) -> str:
        """Execute LLM-generated query code and return the answer.

        Dynamically imports the generated ``query(viewer)`` function, runs it
        with stdout captured, and returns the function's return value along
        with any printed output.

        Args:
            query: The original user question.
            code: Python source code generated by the sub-LLM.
            viewer: The active napari viewer instance.

        Returns:
            A message containing the query response and any captured output,
            or an error description.
        """
        try:
            with asection(f"NapariViewerQueryTool:"):
                with asection(f"Query:"):
                    aprint(query)
                aprint(f"Resulting in code of length: {len(code)}")

                # prepare code:
                code = super()._prepare_code(code)

                # Load the code as module:
                loaded_module = dynamic_import(code)

                # get the function:
                query_function = getattr(loaded_module, "query")

                # Redirect output:
                f = StringIO()
                with redirect_stdout(f):
                    # Run query code:
                    response = query_function(viewer)

                    # Add call to query function and print response:
                    code += f"\n\nresponse = query(viewer)"
                    code += f"\n\nprint(response)"

                    # Add successfully run code to notebook:
                    if self.notebook:
                        self.notebook.add_code_cell(code + "\n\nquery(viewer)")

                    # Come up with a filename:
                    filename = f"generated_code_{self.__class__.__name__}.py"

                    # Add the snippet to the code snippet editor:
                    from napari_chatgpt.microplugin.microplugin_window import (
                        MicroPluginMainWindow,
                    )

                    MicroPluginMainWindow.add_snippet(filename=filename, code=code)

                # Get captured stdout:
                captured_output = f.getvalue()

                # Message:
                if len(captured_output) > 0:
                    message = f"Tool completed query successfully, here is the response:\n\n{response}\n\nand the captured standard output:\n\n{captured_output}\n\n"
                else:
                    message = f"Tool completed query successfully, here is the response:\n\n{response}\n\n"

                with asection(f"Message:"):
                    aprint(message)

                return message

        except Exception as e:
            traceback.print_exc()
            return f"Error: {type(e).__name__} with message: '{str(e)}' occurred while trying to query the napari viewer."  # with code:\n```python\n{code}\n```\n.
