__version__ = "2025.07.28"

# Try to get version from _version.py (generated by hatch-vcs or similar)
try:
    from ._version import version as __version__  # noqa: F811
except ImportError:
    pass  # Use the hardcoded version above

from ._widget import OmegaQWidget

__all__ = ("OmegaQWidget",)
