__version__ = "2026.2.8.1"

# Try to get version from _version.py (generated by hatch-vcs or similar)
try:
    from ._version import version as __version__  # noqa: F811
except ImportError:
    pass  # Use the hardcoded version above

import sys

if sys.platform == "win32":
    for _stream in (sys.stdout, sys.stderr):
        if hasattr(_stream, "reconfigure"):
            _stream.reconfigure(encoding="utf-8", errors="replace")


def __getattr__(name: str):
    if name == "OmegaQWidget":
        from ._widget import OmegaQWidget

        return OmegaQWidget
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = ("OmegaQWidget",)
