__version__ = "2025.07.28"

# Try to get version from _version.py (generated by hatch-vcs or similar)
try:
    from ._version import version as __version__  # noqa: F811
except ImportError:
    pass  # Use the hardcoded version above


def __getattr__(name: str):
    if name == "OmegaQWidget":
        from ._widget import OmegaQWidget

        return OmegaQWidget
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


__all__ = ("OmegaQWidget",)
